### ISSUE TITLE
plugin is not publisheed

### ISSUE THREAD

**Issue by sibelius** [damassi/gatsby-plugin-emit-graphql-types#5]
```
yarn add gatsby-plugin-emit-graphql-types
```

```
yarn add v1.16.0
[1/4] 🔍  Resolving packages...
error No valid versions found for "gatsby-plugin-emit-graphql-types". The package may be unpublished.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by damassi** [comment]
@sibelius - this is intentional due to the caveat in the readme. Until Gratsby can support 3rd party schema extensions in a way that is statically analyizable I didn't want to publish only to end up with a lot of disappointed users. Also, `gatsby-plugin-sharp` is in like every starter, meaning out of the gate this would fail to work and lead to confusion.

**Comment by damassi** [comment]
(Just noticed the readme had a reference to the package / install instructions; updated and replaced with a reference to docs on local plugins.)
